# Spring Boot application-specific config properties to be shared by all
# GeoServer microservices. Imported from geoserver.yml, in order to separate
# application from geoserver configuration.
server:
  tomcat:
    # Maximum number of connections that the server accepts and processes at any given time.
    # Once the limit has been reached, the operating system may still accept connections based on the "acceptCount" property.
    max-connections: ${tomcat.max.connections:8192}
    # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    accept-count: ${tomcat.accept.count:100}
    accesslog.enabled: ${tomcat.accesslog.enabled:false}
    mbeanregistry.enabled: ${tomcat.mbeanregistry.enabled:false}
    threads:
      # Minimum amount of worker threads.
      min-spare: ${tomcat.threads.min.spare:10}
      # Maximum amount of worker threads.
      max: ${tomcat.threads.max:200}

spring:
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.user:guest}
    password: ${rabbitmq.password:guest}
    virtual-host: ${rabbitmq.vhost:}
  cloud:
    bus:
      enabled: true
      id: ${info.instance-id} # use the same instance id for eureka (see service's' bootstrap.yml) and cloud-bus' rabbitmq instance id
      trace.enabled: false #switch on tracing of acks (default off).
    stream:
      bindings:
        springCloudBusOutput:
          destination: geoserver
        springCloudBusInput:
          destination: geoserver
  jackson:
    default-property-inclusion: non-empty
    serialization.indent-output: false #set to true if doing manual testing and want formatted output

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    info.enabled: true
    metrics.enabled: true
    shutdown.enabled: true
    health:
      enabled: true
      probes.enabled: true
      show-details: always
  metrics:
    binders:
      processor.enabled: true
      uptime.enabled: true
      jvm.enabled: true
    enable.all: true
    enable.jvm: true
    export:
      atlas.enabled: false
