# General configuration imports
spring.config.import:
  - geoserver_spring.yml
  - optional:geoserver_logging.yml
  - jndi.yml

spring:
  cache:
    type: caffeine
    caffeine:
      spec: softValues,initialCapacity=10000,maximumSize=10000,recordStats

geoserver:
  debug:
    instanceId: false # Disable instance ID tracking
  acl:
    enabled: ${acl.enabled:false}
    client:
      basePath: ${acl.url:http://acl:8080/acl/api}
      username: ${acl.username:}
      password: ${acl.password:}
      caching: ${acl.caching:true}
      initTimeout: ${acl.initTimeout:10} # Fail fast if ACL is not available
  metrics:
    enabled: true
    instance-id: ${info.instance-id}
  security:
    enabled: true
    authkey: true
    gateway-shared-auth:
      enabled: false
      auto: true
      server: false # True only in the webui_service profile
  catalog:
    advertised: true
    localWorkspace: true
    isolated: true
    secure: true
    caching.enabled: false
  bus:
    enabled: true
    send-events: true
    send-object: ${geoserver.backend.data-directory.enabled}
    send-diff: ${geoserver.backend.data-directory.enabled}
  backend:
    data-directory:
      enabled: ${backend.data-directory:false}
      location: ${GEOSERVER_DATA_DIR:/opt/app/data_directory}
      parallel-loader: true
      eventual-consistency:
        enabled: true
        retries: 25, 25, 50
    jdbcconfig:
      enabled: ${backend.jdbcconfig:false}
      initdb: true
      web.enabled: true
      datasource:
        url: "${jdbcconfig.url:jdbc:postgresql://${jdbcconfig.host:database}:${jdbcconfig.port:5432}/${jdbcconfig.database:geoserver_config}?currentSchema=${jdbcconfig.schema:public}}"
        username: ${jdbcconfig.username:geoserver}
        password: ${jdbcconfig.password:geo5erver}
        driverClassname: org.postgresql.Driver
        minimumIdle: ${jdbcconfig.minConnections:0}
        maximumPoolSize: ${jdbcconfig.maxConnections:8}
        connectionTimeout: ${jdbcconfig.connectionTimeout:250}
        idleTimeout: ${jdbcconfig.idleTimeout:10000}
    pgconfig:
      enabled: ${backend.pgconfig:false}
      initialize: ${pgconfig.initialize:true}
      schema: ${pgconfig.schema:public}
      create-schema: true
      datasource:
        url: "${pgconfig.url:jdbc:postgresql://${pgconfig.host:database}:${pgconfig.port:5432}/${pgconfig.database:geoserver_config}}"
        username: ${pgconfig.username:pgconfig}
        password: ${pgconfig.password:pgconfig}
        driverClassname: org.postgresql.Driver
        minimumIdle: ${pgconfig.minConnections:0}
        maximumPoolSize: ${pgconfig.maxConnections:10}
        connectionTimeout: ${pgconfig.connectionTimeout:2500}
        idleTimeout: ${pgconfig.idleTimeout:30000}

# HTTP Client Proxy for GeoTools
geotools:
  httpclient:
    proxy:
      enabled: true
      http:
        host: ${http.proxyHost:}
        port: ${http.proxyPort:}
        user: ${http.proxyUser:}
        password: ${http.proxyPassword:}
        nonProxyHosts: ${http.nonProxyHosts:localhost.*}
      https:
        host: ${https.proxyHost:${geotools.httpclient.proxy.http.host}}
        port: ${https.proxyPort:${geotools.httpclient.proxy.http.port}}
        user: ${https.proxyUser:${geotools.httpclient.proxy.http.user}}
        password: ${https.proxyPassword:${geotools.httpclient.proxy.http.password}}
        nonProxyHosts: ${https.nonProxyHosts:${geotools.httpclient.proxy.http.nonProxyHosts}}

# Service Targets
targets:
  acl: http://acl:8080
  wfs: http://wfs:8080
  wms: http://wms:8080
  wcs: http://wcs:8080
  wps: http://wps:8080
  rest: http://rest:8080
  gwc: http://gwc:8080
  webui: http://webui:8080

# GeoWebCache Configuration
gwc:
  enabled: true
  cache-directory: ${GEOWEBCACHE_CACHE_DIR:${geoserver.backend.data-directory.location}/gwc}
  rest-config: true
  web-ui: true
  wms-integration: true
  services:
    wmts: true
    tms: true
    wms: true
    kml: true
    gmaps: true
    mgmaps: true
  blobstores:
    azure: true
    s3: true

# ACL Service Profile
---
spring.config.activate.on-profile: acl
acl.enabled: true
acl.url: http://acl:8080/acl/api
acl.username: geoserver
acl.password: s3cr3t
acl.caching: true
acl.initTimeout: 10

# Backend Profiles
---
spring.config.activate.on-profile: datadir
backend.data-directory: true

---
spring.config.activate.on-profile: jdbcconfig
backend.jdbcconfig: true
geoserver.catalog.caching.enabled: false

---
spring.config.activate.on-profile: pgconfig
backend.pgconfig: true
jndi.pgconfig.enabled: true

# Microservice Profiles
---
spring.config.activate.on-profile: wfs_service
geoserver.security.layergroup-containmentcache: false

---
spring.config.activate.on-profile: wms_service
geoserver.security.layergroup-containmentcache: true

---
spring.config.activate.on-profile: wcs_service
geoserver.security.layergroup-containmentcache: false

---
spring.config.activate.on-profile: wps_service
geoserver.security.layergroup-containmentcache: false

---
spring.config.activate.on-profile: restconfig_service
geoserver.security.layergroup-containmentcache: false

---
spring.config.activate.on-profile: gwc_service
geoserver.security.layergroup-containmentcache: true

---
spring.config.activate.on-profile: webui_service
geoserver:
  security:
    layergroup-containmentcache: true
    gateway-shared-auth.server: false
  web-ui:
    acl.enabled: ${geoserver.acl.enabled}
    file-browser.hide-file-system: ${webui.hide-filesystem:false}
    security.enabled: true
    wfs.enabled: true
    wms.enabled: true
    wcs.enabled: true
    wps.enabled: true
    gwc.enabled: true
    extensions.importer.enabled: false
    demos:
      enabled: true
      wps-request-builder: true
      wcs-request-builder: true
      demo-requests: true
      srs-list: true
      reprojection-console: true
      layer-preview-page.enabled: true
      common-formats:
        open-layers: true
        gml: true
        kml: true
    tools.enabled: true
